# This is a basic workflow to help you get started with Actions

name: learn-github-actions

# Controls when the workflow will run
on:
  # Triggers the workflow at a specific time
  schedule:
    - cron: '0 15 * * 4'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test_all"
  test_all:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: My time test
        run: echo "This step will be run on Thursdays at 16 CET"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Lint content
        id: lint_test_output
        env:
          my-log: $GITHUB_STEP_SUMMARY
        uses: DavidAnson/markdownlint-cli2-action@v7 >> $GITHUB_OUTPUT
        continue-on-error: true            
        with:
          command: config
          globs: |
            .markdownlint-cli2.yaml
            content/en/docs/**/*.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Lint docs
          title: '[Auto] Lint docs'
          body: |
            - Lint docs ${{join(steps.lint_test_output.outputs.*, '\n')}}
          branch: lint-docs
