# This is a basic workflow to help you get started with Actions

name: learn-jobs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # 1st job: echo test
  echo_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: My test
        run: echo "This is an ECHO test"
  # 2nd job: check out repo
  checkout_repo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
  # 3rd job: run linter on content
  lint_content:
    needs: checkout_repo
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Lint content
        uses: DavidAnson/markdownlint-cli2-action@v6
        continue-on-error: true
        with:
          command: config
          globs: |
            .markdownlint-cli2.yaml
            content/en/docs/**/*.md
  # 4th job: create PR
  create_pr:
    needs: [checkout_repo, lint_content]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Lint files
          title: '[Auto] Lint files'
          body: |
            - Lint files
          branch: lint-files
