# This is a basic workflow to help you get started with Actions
name: echo-test

# Controls when the workflow will run
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test_all"
  test_all:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: run-some-command
        run: echo "Hello world!" | tee ./tmp.log
      - name: echo-log
        run: cat ./tmp.log
      - name: Lint content
        id: lint_test_output
        uses: DavidAnson/markdownlint-cli2-action@v7
        continue-on-error: true            
        with:
          command: config
          globs: |
            .markdownlint-cli2.yaml
            content/en/docs/**/*.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Lint docs
          title: '[Auto] Lint docs'
          body: |
            - Lint docs ${{(cat ./tmp.log)}}
          branch: lint-docs
