# This is a basic workflow to help you get started with Actions
name: Auto lint content

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 20 1 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint-pr"
  lint-pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@v3
      # Installs node v16 in runner environment
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install markdown linter
        run: npm install markdownlint-cli2 --global
      - name: Run markdownlint-cli2
        run: |
          markdownlint-cli2-config ".markdownlint-cli2.yaml" "content/en/docs/**/*.md" "!content/en/docs/developerportal/test/indentation.md" 2>&1 | tee ./tmp.log
      - name: Grab markdownlint log
        id: echo-log
        run: |
          chmod +x ./tmp.log
          VER=$(cat << EOF ./tmp.log)
          echo "VER<<EOF" >> $GITHUB_ENV
          echo "$VER" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Run markdownlint-cli2 on docs
          title: '[Auto] Lint docs'
          body: |
            ${{ env.VER }}
          branch: lint-docs
          assignees: NatasaKralj
          reviewers: NatasaKralj
          labels: Internal WIP
          add-paths: |
            content/en/docs/**/*.md
